"""empty message

Revision ID: 07d0e44dc021
Revises: 
Create Date: 2018-07-16 04:34:24.474203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07d0e44dc021'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maba',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nik', sa.String(length=20), nullable=False),
    sa.Column('nama', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('prodi1', sa.String(length=15), nullable=False),
    sa.Column('prodi2', sa.String(length=15), nullable=False),
    sa.Column('no_seleksi', sa.String(length=10), nullable=True),
    sa.Column('jenis_kelamin', sa.String(length=15), nullable=False),
    sa.Column('ttl', sa.String(length=100), nullable=False),
    sa.Column('alamat', sa.String(length=100), nullable=False),
    sa.Column('agama', sa.String(length=10), nullable=False),
    sa.Column('no_hp', sa.String(length=15), nullable=True),
    sa.Column('asal_sekolah', sa.String(length=30), nullable=False),
    sa.Column('tahun_lulus', sa.Integer(), nullable=False),
    sa.Column('jurusan_sma', sa.String(length=20), nullable=False),
    sa.Column('nama_wali', sa.String(length=50), nullable=False),
    sa.Column('pekerjaan_wali', sa.String(length=30), nullable=False),
    sa.Column('penghasilan_wali', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('maba')
    # ### end Alembic commands ###
